-- MySQL Script generated by MySQL Workbench
-- 01/31/16 17:28:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema waoo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema waoo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `waoo` DEFAULT CHARACTER SET utf8 ;
USE `waoo` ;

-- -----------------------------------------------------
-- Table `waoo`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`tipousuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`bancos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`bancos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tipo` INT NOT NULL DEFAULT 1,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `fecharegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idbanco` INT NOT NULL DEFAULT 0,
  `numerocuenta` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tipouser_idx` (`tipo` ASC),
  INDEX `banco_idx` (`idbanco` ASC),
  CONSTRAINT `tipouser`
    FOREIGN KEY (`tipo`)
    REFERENCES `waoo`.`tipousuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `banco`
    FOREIGN KEY (`idbanco`)
    REFERENCES `waoo`.`bancos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`materia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fecharegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`rating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idasistente` INT NOT NULL DEFAULT 0,
  `puntaje` TINYINT NOT NULL DEFAULT 0,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idusuario` INT NOT NULL DEFAULT 0,
  `comentario` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuariocalif_idx` (`idusuario` ASC),
  INDEX `asistente_idx` (`idasistente` ASC),
  CONSTRAINT `usuariocalif`
    FOREIGN KEY (`idusuario`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `asistente`
    FOREIGN KEY (`idasistente`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `waoo`.`asistentemateria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`asistentemateria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idasistente` INT NOT NULL DEFAULT 0,
  `idmateria` INT NOT NULL DEFAULT 0,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `asistente_idx` (`idasistente` ASC),
  INDEX `materia_idx` (`idmateria` ASC),
  CONSTRAINT `asistentemat`
    FOREIGN KEY (`idasistente`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `materiaasist`
    FOREIGN KEY (`idmateria`)
    REFERENCES `waoo`.`materia` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;
