-- MySQL Script generated by MySQL Workbench
-- 01/31/16 17:28:49
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema waoo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema waoo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `waoo` DEFAULT CHARACTER SET utf8 ;
USE `waoo` ;

-- -----------------------------------------------------
-- Table `waoo`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`tipousuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`bancos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`bancos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nickname` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `nombres` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `tipo` INT NOT NULL DEFAULT 1,
  `estado` TINYINT NOT NULL DEFAULT 1,
  `fecharegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idbanco` INT NOT NULL DEFAULT 0,
  `numerocuenta` VARCHAR(45) NOT NULL,
  `celular` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tipouser_idx` (`tipo` ASC),
  INDEX `banco_idx` (`idbanco` ASC),
  CONSTRAINT `tipouser`
    FOREIGN KEY (`tipo`)
    REFERENCES `waoo`.`tipousuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `banco`
    FOREIGN KEY (`idbanco`)
    REFERENCES `waoo`.`bancos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`materia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `fecharegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`rating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idasistente` INT NOT NULL DEFAULT 0,
  `puntaje` TINYINT NOT NULL DEFAULT 0,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idusuario` INT NOT NULL DEFAULT 0,
  `comentario` TEXT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `usuariocalif_idx` (`idusuario` ASC),
  INDEX `asistente_idx` (`idasistente` ASC),
  CONSTRAINT `usuariocalif`
    FOREIGN KEY (`idusuario`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `asistente`
    FOREIGN KEY (`idasistente`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`estado` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `waoo`.`asistentemateria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`asistentemateria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idasistente` INT NOT NULL DEFAULT 0,
  `idmateria` INT NOT NULL DEFAULT 0,
  `estado` TINYINT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `asistente_idx` (`idasistente` ASC),
  INDEX `materia_idx` (`idmateria` ASC),
  CONSTRAINT `asistentemat`
    FOREIGN KEY (`idasistente`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `materiaasist`
    FOREIGN KEY (`idmateria`)
    REFERENCES `waoo`.`materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`trabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`trabajo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL DEFAULT 0,
  `idmateria` INT NOT NULL DEFAULT 0,
  `titulo` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `idasistente` INT NOT NULL DEFAULT 0,
  `numcomprobante` VARCHAR(45) NOT NULL,
  `fecharegistro` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `fecharesuelto` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `estado` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`),
  INDEX `usuario_idx` (`idusuario` ASC),
  INDEX `materia_idx` (`idmateria` ASC),
  INDEX `asistente_idx` (`idasistente` ASC),
  CONSTRAINT `usuariot`
    FOREIGN KEY (`idusuario`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `materiat`
    FOREIGN KEY (`idmateria`)
    REFERENCES `waoo`.`materia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `asistentet`
    FOREIGN KEY (`idasistente`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`trabajoarchivos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`trabajoarchivos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idtrabajo` INT NOT NULL DEFAULT 0,
  `idusuario` INT NOT NULL DEFAULT 0,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `archivo` MEDIUMBLOB NOT NULL,
  `tipoarchivo` VARCHAR(45) NOT NULL,
  `extension` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `trabajo_idx` (`idtrabajo` ASC),
  INDEX `usuario_idx` (`idusuario` ASC),
  CONSTRAINT `trabajo`
    FOREIGN KEY (`idtrabajo`)
    REFERENCES `waoo`.`trabajo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`reasignacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`reasignacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idtrabajo` INT NOT NULL DEFAULT 0,
  `idasistenteprevio` INT NOT NULL DEFAULT 0,
  `idasistentenuevo` INT NOT NULL DEFAULT 0,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `idreasigna` INT NOT NULL DEFAULT 0,
  `comentario` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `idtrabajore_idx` (`idtrabajo` ASC),
  INDEX `idasistant_idx` (`idasistenteprevio` ASC),
  INDEX `idasistnue_idx` (`idasistentenuevo` ASC),
  INDEX `idreasigna_idx` (`idreasigna` ASC),
  CONSTRAINT `idtrabajore`
    FOREIGN KEY (`idtrabajo`)
    REFERENCES `waoo`.`trabajo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idasistant`
    FOREIGN KEY (`idasistenteprevio`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idasistnue`
    FOREIGN KEY (`idasistentenuevo`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idreasigna`
    FOREIGN KEY (`idreasigna`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`tipolog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`tipolog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`trabajolog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`trabajolog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idtrabajo` INT NOT NULL,
  `idusuario` INT NOT NULL,
  `tipolog` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX `idtrabl_idx` (`idtrabajo` ASC),
  INDEX `idusuariol_idx` (`idusuario` ASC),
  INDEX `idtipologtr_idx` (`tipolog` ASC),
  CONSTRAINT `idtrabl`
    FOREIGN KEY (`idtrabajo`)
    REFERENCES `waoo`.`trabajo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idusuarioltr`
    FOREIGN KEY (`idusuario`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idtipologtr`
    FOREIGN KEY (`tipolog`)
    REFERENCES `waoo`.`tipolog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`ofertatrabajo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`ofertatrabajo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idasistente` INT NOT NULL DEFAULT 0,
  `idtrabajo` INT NOT NULL DEFAULT 0,
  `valor` INT NOT NULL DEFAULT 0,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idasistoftr_idx` (`idasistente` ASC),
  INDEX `idtraboftr_idx` (`idtrabajo` ASC),
  CONSTRAINT `idasistoftr`
    FOREIGN KEY (`idasistente`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idtraboftr`
    FOREIGN KEY (`idtrabajo`)
    REFERENCES `waoo`.`trabajo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `waoo`.`notificacionesusuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waoo`.`notificacionesusuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idusuario` INT NOT NULL DEFAULT 0,
  `mensaje` TEXT NOT NULL,
  `fecha` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `leido` INT NOT NULL DEFAULT 0,
  `idtrabajo` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  INDEX `idusuarionotif_idx` (`idusuario` ASC),
  INDEX `idtrabnotif_idx` (`idtrabajo` ASC),
  CONSTRAINT `idusuarionotif`
    FOREIGN KEY (`idusuario`)
    REFERENCES `waoo`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idtrabnotif`
    FOREIGN KEY (`idtrabajo`)
    REFERENCES `waoo`.`trabajo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
